"""Regression tests for the stream-recorder architecture review."""

from __future__ import annotations

import asyncio

import pytest

from scripts.stream_recorder import discovery, orchestrator
from scripts.stream_recorder.orchestrator import Camera
from scripts.stream_recorder.hls import HlsVariant
from scripts.stream_recorder.sources import Source


def test_static_hls_extraction_ignores_non_stream_service_hosts() -> None:
    """Static discovery must reject Google/Facebook service URLs while keeping webcam CDNs."""
    html = """
    <script>
      const analytics = 'https://fonts.googleapis.com/tracker.m3u8';
      const social = 'https://www.facebook.com/video/playlist.m3u8';
      const camera = 'https://s24.ipcamlive.com/streams/camera/stream.m3u8';
    </script>
    """

    assert discovery.extract_m3u8_urls(html, "https://example.test/") == {
        "https://s24.ipcamlive.com/streams/camera/stream.m3u8"
    }


@pytest.mark.asyncio
async def test_fetch_text_uses_supplied_async_http_client() -> None:
    """HTTP discovery must use a true async client instead of the default thread pool."""

    class Response:
        """Model the subset of an httpx response used by ``fetch_text``."""

        text = "camera"
        url = "https://example.test/final"

        def raise_for_status(self) -> None:
            """Model a successful HTTP response."""
            return None

    class Client:
        """Record asynchronous GET calls made by ``fetch_text``."""

        def __init__(self) -> None:
            """Initialize the request log."""
            self.urls: list[str] = []

        async def get(self, url: str) -> Response:
            """Return a successful synthetic response without using worker threads."""
            self.urls.append(url)
            await asyncio.sleep(0)
            return Response()

    client = Client()
    text, final_url = await discovery.fetch_text(
        "https://example.test/start",
        client=client,
    )

    assert text == "camera"
    assert final_url == "https://example.test/final"
    assert client.urls == ["https://example.test/start"]


@pytest.mark.asyncio
async def test_browser_observes_frame_tree_without_reopening_iframe_urls() -> None:
    """One source must use one Playwright page and never reopen iframe URLs as targets."""
    stream_url = "https://cdn.example.test/live/camera.m3u8"
    pages_created = 0

    class Request:
        """Represent one HLS request generated by an embedded frame."""

        url = stream_url

    class Page:
        """Model a root page whose embedded frame emits an HLS request."""

        def __init__(self) -> None:
            """Initialize the request callback slot."""
            self.request_callback = None

        def on(self, event: str, callback) -> None:
            """Capture the request callback registered by browser discovery."""
            assert event == "request"
            self.request_callback = callback

        async def goto(self, _url: str, **_kwargs) -> None:
            """Emit the frame-tree HLS request while loading the root page."""
            assert self.request_callback is not None
            self.request_callback(Request())

        async def wait_for_timeout(self, _milliseconds: int) -> None:
            """Yield once without adding test latency."""
            await asyncio.sleep(0)

        def locator(self, _selector: str):
            """Fail if production code tries to enumerate/reopen iframe URLs."""
            raise AssertionError("iframe URLs must not be crawled as separate browser targets")

        async def close(self) -> None:
            """Close the synthetic page immediately."""
            return None

    class Context:
        """Create root browser pages and count renderer allocations."""

        async def new_page(self) -> Page:
            """Create exactly one page for the source."""
            nonlocal pages_created
            pages_created += 1
            return Page()

    session = discovery.BrowserSession(
        context=Context(),
        page_semaphore=asyncio.Semaphore(2),
    )

    streams = await discovery.discover_browser(
        "https://example.test/source",
        browser=session,
        settle_ms=0,
    )

    assert streams == {stream_url}
    assert pages_created == 1


@pytest.mark.asyncio
async def test_real_browser_session_uses_isolated_context_per_source() -> None:
    """Concurrent sources share one Chromium process but never share browser session state."""
    contexts_created = 0
    contexts_closed = 0
    active_contexts = 0
    max_active_contexts = 0

    class Page:
        """Model one source tab living inside its own BrowserContext."""

        frames: list[object] = []

        def on(self, _event: str, _callback) -> None:
            """Accept request listeners without emitting HLS."""
            return None

        async def goto(self, _url: str, **_kwargs) -> None:
            """Keep sources overlapped long enough to exercise the semaphore."""
            await asyncio.sleep(0.02)

        async def close(self) -> None:
            """Close the source tab immediately."""
            return None

    class Context:
        """Represent one isolated source session created by the shared Chromium process."""

        async def new_page(self) -> Page:
            """Create the only page used by this isolated source context."""
            return Page()

        async def close(self) -> None:
            """Release this source session and update concurrency accounting."""
            nonlocal contexts_closed, active_contexts
            contexts_closed += 1
            active_contexts -= 1

    class Browser:
        """Create isolated contexts while representing one shared Chromium process."""

        async def new_context(self) -> Context:
            """Create a new isolated source context and track concurrent context count."""
            nonlocal contexts_created, active_contexts, max_active_contexts
            contexts_created += 1
            active_contexts += 1
            max_active_contexts = max(max_active_contexts, active_contexts)
            return Context()

    session = discovery.BrowserSession(
        context=None,
        browser=Browser(),
        page_semaphore=asyncio.Semaphore(2),
    )

    await asyncio.gather(*(
        discovery._visit_browser_target(
            session,
            f"https://example.test/source-{index}",
            settle_ms=0,
        )
        for index in range(4)
    ))

    assert contexts_created == 4
    assert contexts_closed == 4
    assert max_active_contexts == 2


@pytest.mark.asyncio
async def test_browser_retries_one_clean_empty_visit_in_fresh_source_context(monkeypatch) -> None:
    """An intermittent player that cleanly emits no HLS gets exactly one bounded fresh retry."""
    stream_url = "https://hd-auth.skylinewebcams.com/live.m3u8?a=fresh"
    calls = 0

    async def fake_visit(*_args, **_kwargs) -> set[str]:
        """Miss HLS once, then model a fresh isolated source session succeeding."""
        nonlocal calls
        calls += 1
        return set() if calls == 1 else {stream_url}

    monkeypatch.setattr(discovery, "_visit_browser_target", fake_visit)
    session = discovery.BrowserSession(
        context=object(),
        page_semaphore=asyncio.Semaphore(1),
    )

    streams = await discovery.discover_browser(
        "https://example.test/intermittent-player",
        browser=session,
    )

    assert calls == 2
    assert streams == {stream_url}


@pytest.mark.asyncio
async def test_concurrent_camera_rediscovery_is_coalesced_per_source(monkeypatch) -> None:
    """Camera failures from one source must await one shared in-flight rediscovery."""
    source = Source("1", "Square", "City", "Country", "https://example.test/page")
    calls = 0
    release = asyncio.Event()
    cameras = [
        Camera("camera-001", HlsVariant("https://example.test/a.m3u8")),
        Camera("camera-002", HlsVariant("https://example.test/b.m3u8")),
    ]

    async def fake_discover(*_args, **_kwargs) -> list[Camera]:
        """Block the first rediscovery so concurrent camera requests overlap."""
        nonlocal calls
        calls += 1
        await release.wait()
        return cameras

    monkeypatch.setattr(orchestrator, "discover_source_cameras", fake_discover)
    coordinator = orchestrator.SourceRediscovery(source, http=object(), browser=None)

    first = asyncio.create_task(coordinator.camera("camera-001"))
    second = asyncio.create_task(coordinator.camera("camera-002"))
    await asyncio.sleep(0)
    release.set()

    first_camera, second_camera = await asyncio.gather(first, second)
    assert first_camera == cameras[0]
    assert second_camera == cameras[1]
    assert calls == 1
